services:
  duplicati:
    container_name: duplicati
    restart: unless-stopped
    env_file:
      - ./duplicati/config.ini
      - ./env/duplicati_${ENV}.env
    volumes:
      - duplicati_data:/data
      - /var/lib/docker/volumes:/volumes-source # Mount docker volumes folder as backup source
      - /home/ricardo:/home-source # Mount home folder as backup source

volumes:
  duplicati_data:
    name: "duplicati_data"
