services:
  postgres:
    container_name: postgres
    env_file:
      - ./postgres/config.ini
      - ./env/postgres_${ENV}.env

    command: -c config_file=/etc/postgresql.conf
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql.conf
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    name: postgres_data
